name: mobile_protege_meu_cerrado
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  shared_preferences: ^2.0.15
  fl_chart: ^0.69.0
  intl: ^0.19.0
  dio: ^5.0.0
  carousel_slider: ^5.0.0
  table_calendar: ^3.1.2
  flutter_iconpicker: ^4.0.1
  flutter_slidable: ^3.1.1
  animations: ^2.0.11
  dropdown_button2: ^2.3.9
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_native_splash: ^2.2.10 # Adicione aqui a versão do pacote
  mask_text_input_formatter: ^2.9.0
  geolocator: ^13.0.2
  fluttertoast: ^8.2.8
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/icone.png
    - assets/images/cerrado.jpeg
    - assets/images/animal1.jpg
    - assets/images/animal2.jpg
    - assets/images/animal3.jpg
    - assets/images/animal4.jpg
    - assets/images/onBoardingF1.png
    - assets/images/onBoardingF2.png
    - assets/images/onBoardingF3.png
    - assets/images/btnImage.png
    - assets/images/btnImage2.png
    - assets/images/logo_simples_verde.png
    - assets/images/logo_complexa.png

  uses-material-design: true

  fonts:
    - family: MavenPro
      fonts:
        - asset: fonts/MavenPro-Regular.ttf
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-Regular.ttf

flutter_native_splash:
  color: "#147454" # Cor de fundo
  image: assets/images/icone.png # Caminho para sua logo
  android: true
  ios: true
  web: false # Caso não seja necessário para web
  # Configurações opcionais para personalizar a logo
  android_gravity: center # Alinhamento da logo no Android
  ios_content_mode: center # Alinhamento da logo no iOS
  fullscreen: true # Ativa a splash screen em tela cheia

