name: mobile_protege_meu_cerrado
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.0.0
  dropdown_button2: ^2.3.9
  firebase_analytics: ^11.3.5
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  fl_chart: ^0.69.0
  flutter_dotenv: ^5.2.1
  flutter_iconpicker: ^4.0.1
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.2.10
  flutter_secure_storage: ^9.2.2
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.16
  fluttertoast: ^8.2.8
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  provider: ^6.1.2
  shared_preferences: ^2.0.15
  table_calendar: ^3.1.2
  curved_navigation_bar: ^1.0.6
  image: 4.3.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/icone.png
    - assets/images/cerrado.jpeg
    - assets/images/animal1.jpg
    - assets/images/animal2.jpg
    - assets/images/animal3.jpg
    - assets/images/animal4.jpg
    - assets/images/onBoardingF1.png
    - assets/images/onBoardingF2.png
    - assets/images/onBoardingF3.png
    - assets/images/btnImage.png
    - assets/images/btnImage2.png
    - assets/images/logo_simples_verde.png
    - assets/images/logo_complexa.png
    - assets/images/fundonovo.png
    - assets/images/queimada1.jpeg
    - assets/images/queimada2.jpg
    - assets/images/queimada3.jpg
    - assets/images/segunda2.svg
    - assets/images/primeira1.svg
    - assets/images/terceira3.svg

  uses-material-design: true

  fonts:
    - family: MavenPro
      fonts:
        - asset: fonts/MavenPro-Regular.ttf
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-Regular.ttf

flutter_native_splash:
  color: "#147454" # Cor de fundo
  image: assets/images/icone.png # Caminho para sua logo
  android: true
  ios: true
  web: false # Caso não seja necessário para web
  # Configurações opcionais para personalizar a logo
  android_gravity: center # Alinhamento da logo no Android
  ios_content_mode: center # Alinhamento da logo no iOS
  fullscreen: true # Ativa a splash screen em tela cheia

